In [4]:
def lerp_color(color1: str, color2: str, t: float) -> str:
        if color1.startswith('#'):
            color1 = color1[1:]
        if color2.startswith('#'):
            color2 = color2[1:]
        # 将16进制颜色值转换为RGB值
        rgb1 = tuple(int(color1[i:i+2], 16) for i in (0, 2, 4))
        rgb2 = tuple(int(color2[i:i+2], 16) for i in (0, 2, 4))

        # 对每个RGB通道进行线性插值
        rgb = tuple(int(rgb1[i] + t * (rgb2[i] - rgb1[i])) for i in range(3))

        # 将RGB值转换回16进制形式
        return '#{:02x}{:02x}{:02x}'.format(*rgb)

In [6]:
lerp_color("#7B287D","#1d3557",0.5)


'#4c2e6a'

In [11]:
import torch
import numpy as np

In [21]:
sample = torch.ones([7, 2])
noise = torch.ones([10] + list(sample.size()))
_noise_scales_th = torch.FloatTensor(np.geomspace(start=5, stop=0.1, num=10))

# obj = (d/2) * torch.mean((self.score_net(perturbed_samples.view([-1, d])) + noise.view([-1, d]))**2)


In [25]:
_noise_scales_th

tensor([5.0000, 3.2374, 2.0961, 1.3572, 0.8788, 0.5690, 0.3684, 0.2385, 0.1544,
        0.1000])

In [23]:
noise * _noise_scales_th.reshape([-1, 1, 1])

tensor([[[5.0000, 5.0000],
         [5.0000, 5.0000],
         [5.0000, 5.0000],
         [5.0000, 5.0000],
         [5.0000, 5.0000],
         [5.0000, 5.0000],
         [5.0000, 5.0000]],

        [[3.2374, 3.2374],
         [3.2374, 3.2374],
         [3.2374, 3.2374],
         [3.2374, 3.2374],
         [3.2374, 3.2374],
         [3.2374, 3.2374],
         [3.2374, 3.2374]],

        [[2.0961, 2.0961],
         [2.0961, 2.0961],
         [2.0961, 2.0961],
         [2.0961, 2.0961],
         [2.0961, 2.0961],
         [2.0961, 2.0961],
         [2.0961, 2.0961]],

        [[1.3572, 1.3572],
         [1.3572, 1.3572],
         [1.3572, 1.3572],
         [1.3572, 1.3572],
         [1.3572, 1.3572],
         [1.3572, 1.3572],
         [1.3572, 1.3572]],

        [[0.8788, 0.8788],
         [0.8788, 0.8788],
         [0.8788, 0.8788],
         [0.8788, 0.8788],
         [0.8788, 0.8788],
         [0.8788, 0.8788],
         [0.8788, 0.8788]],

        [[0.5690, 0.5690],
         [0.5690, 

In [37]:
perturbed_samples = noise *_noise_scales_th.reshape([-1, 1, 1]) + torch.stack([sample] * 10, dim = 0)
d = 2

In [38]:
perturbed_samples

tensor([[[6.0000, 6.0000],
         [6.0000, 6.0000],
         [6.0000, 6.0000],
         [6.0000, 6.0000],
         [6.0000, 6.0000],
         [6.0000, 6.0000],
         [6.0000, 6.0000]],

        [[4.2374, 4.2374],
         [4.2374, 4.2374],
         [4.2374, 4.2374],
         [4.2374, 4.2374],
         [4.2374, 4.2374],
         [4.2374, 4.2374],
         [4.2374, 4.2374]],

        [[3.0961, 3.0961],
         [3.0961, 3.0961],
         [3.0961, 3.0961],
         [3.0961, 3.0961],
         [3.0961, 3.0961],
         [3.0961, 3.0961],
         [3.0961, 3.0961]],

        [[2.3572, 2.3572],
         [2.3572, 2.3572],
         [2.3572, 2.3572],
         [2.3572, 2.3572],
         [2.3572, 2.3572],
         [2.3572, 2.3572],
         [2.3572, 2.3572]],

        [[1.8788, 1.8788],
         [1.8788, 1.8788],
         [1.8788, 1.8788],
         [1.8788, 1.8788],
         [1.8788, 1.8788],
         [1.8788, 1.8788],
         [1.8788, 1.8788]],

        [[1.5690, 1.5690],
         [1.5690, 

In [39]:
perturbed_samples.view(-1, 2)

tensor([[6.0000, 6.0000],
        [6.0000, 6.0000],
        [6.0000, 6.0000],
        [6.0000, 6.0000],
        [6.0000, 6.0000],
        [6.0000, 6.0000],
        [6.0000, 6.0000],
        [4.2374, 4.2374],
        [4.2374, 4.2374],
        [4.2374, 4.2374],
        [4.2374, 4.2374],
        [4.2374, 4.2374],
        [4.2374, 4.2374],
        [4.2374, 4.2374],
        [3.0961, 3.0961],
        [3.0961, 3.0961],
        [3.0961, 3.0961],
        [3.0961, 3.0961],
        [3.0961, 3.0961],
        [3.0961, 3.0961],
        [3.0961, 3.0961],
        [2.3572, 2.3572],
        [2.3572, 2.3572],
        [2.3572, 2.3572],
        [2.3572, 2.3572],
        [2.3572, 2.3572],
        [2.3572, 2.3572],
        [2.3572, 2.3572],
        [1.8788, 1.8788],
        [1.8788, 1.8788],
        [1.8788, 1.8788],
        [1.8788, 1.8788],
        [1.8788, 1.8788],
        [1.8788, 1.8788],
        [1.8788, 1.8788],
        [1.5690, 1.5690],
        [1.5690, 1.5690],
        [1.5690, 1.5690],
        [1.5

In [40]:
noise.view([-1, 2])

tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1

In [28]:
import sys
sys.path.append('../')
from nets import FCNN

In [31]:
net = FCNN(dims=[2, 2048, 2048, 2048, 2048, 2], batchnorm=True)

In [36]:
print(sample)
net(sample)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]])


tensor([[0.0173, 0.0008],
        [0.0173, 0.0008],
        [0.0173, 0.0008],
        [0.0173, 0.0008],
        [0.0173, 0.0008],
        [0.0173, 0.0008],
        [0.0173, 0.0008]], grad_fn=<AddmmBackward0>)